spring.main.allow-bean-definition-overriding=true
debug=true
server.tomcat.basedir=./temp
spring.datasource.url=jdbc:sqlserver://VASIVBM:1433;databaseName=Familie_Diploma;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Permitem fișiere de până la 10MB (sau cât crezi că ai nevoie)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB